### PR TITLE
Move filters to ob1k-core-extras

### PR DESCRIPTION
**Pull request by eranharel**
Moving to avoid dependency cycle when introducing discovery to ob1k-cache

### CODE REVIEW

**Comment by marenzo** [comment]
LGTM
but give some few more minutes to think about a better name :)

**Comment by langera** [comment]
I agree. what does "core-extra" really mean?
IMO its a strong hint that there's nothing these classes really share and they should be in different modules (ie. metric, cache etc.)

**Comment by eranharel** [comment]
I'm not attached to the name...

WRT moving the filter classes to other modules - it's possible to do that for the caching filter, but not for the metics filters, as these will force a cyclic dependency between core and metrics.

I think it can be an option to just move the CachingFilter for now, but it doesn't mean we won't have to create an additional lib in the future.

**Comment by eranharel** [comment]
Will just move the caching filter to ob1k-cache for now

**Pull request closed without merging**
