### PR TITLE
Making batchUnordered much less stack hungry.

### PR DESCRIPTION
**Pull request by ahadadi**

### CODE REVIEW

**Comment by haski** [comment]
Not sure I understand the problem. The implementation is not really recursive since every call is done after the value have arrived and the stack has collapsed.
The only scenario that can cause SOF is eager futures and a producer that produces a value immediately, if that's the case you don't need to use futures at all.
Can you please provide a test that demonstrate the problem ?

**Comment by ahadadi** [comment]
Consider the following scenario:
Programmer X calls some end point and gets back a ComposableFuture. He calls batchUnordered using a producer that generates a bunch of these futures and everything works. 2 months later X decides to use LocalAsyncCache on top of the end point. This local cache averages a 95% hit rate. Now some of his futures are eager and return a value immediately and some are not. This poor guy is going to experience intermittent StackOverflowErrors.

**Comment by ahadadi** [comment]
Here's a test that fails (actually hangs due to the SOE and ob1k handling of Errors) since delegateHandler is false.

```
List<Integer> nums = IntStream.range(0, 2000).boxed().collect(toList());
batchUnordered(nums, 2, result -> ComposableFutures.submit(false, () -> result)).get();
```

**Comment by ahadadi** [comment]
Hi @haski, did you manage to reproduce the StackOverflowError using the test?

**Comment by ahadadi** [comment]
Pushed to master

**Pull request closed without merging**
